<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function userregistration_menu() {
    $items = array();
    $items['userregister'] = array(
        'title' => 'User Registration',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_userregistration_wizard'),
        'access callback' => 'user_is_anonymous',
        'description' => 'User Registration',
        'file' => 'userregistration_wizard.inc',
    );
    return $items;
}
//hook_form_FORM_ID_alter
function userregistration_form_user_login_block_alter(&$form,&$form_state){
   
    $items = array();
  if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
    $items[] = l(t('Create new account'), 'userregister', array('attributes' => array('title' => t('Create a new user account.'))));
  }
  $items[] = l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
  $form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
  
  
}
