<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function userregistration_menu() {
    $items = array();
    $items['userregister'] = array(
        'title' => 'User Registration',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_userregistration_wizard'),
        'access callback' => 'user_is_anonymous',
        'description' => 'User Registration',
        'file' => 'userregistration_wizard.inc',
    );
    return $items;
}
//hook_form_FORM_ID_alter
function userregistration_form_user_login_block_alter(&$form,&$form_state){
   
    $items = array();
  if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
    $items[] = l(t('Create new account'), 'userregister', array('attributes' => array('title' => t('Create a new user account.'))));
  }
  $items[] = l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
  $form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
  
  
}


/**
 * Implements mymodule_thumb_upload theme callback.
 */
function theme_userregistration_thumb_upload($variables) {

    $element = $variables['element'];

    if (isset($element['#file']->uri)) {
        $output = '<div id="edit-logo-ajax-wrapper"><div class="form-item form-type-managed-file form-item-logo"><span class="file">';
        $output .= '<img height="50px" src="' . image_style_url('thumbnail', $element['#file']->uri) . '" />';
        $output .= '</span><input type="submit" id="edit-' . $element['#name'] . '-remove-button" name="' . $element['#name'] . '_remove_button" value="Remove" class="form-submit ajax-processed">';
        $output .= '<input type="hidden" name="' . $element['#name'] . '[fid]" value="' . $element['#file']->fid . '"></div></div>';
        return $output;
    }
}

/**
 * Implements hook_theme().
 */
function userregistration_theme() {
  return array(
    'userregistration_thumb_upload' => array(
      'render element' => 'element',
    )
  );
}