<?php

/** * Implements hook_menu_alter(). */
function sharemyride_registration_menu_alter(&$items) {
    drupal_set_message('module');
    // Ctools registration wizard for standard registration.
    //  // Overrides default router item defined by core user module. 
    $items['user/register']['page callback'] = array('sharemyride_registration_ctools_wizard');
    // Pass the "first" step key to start the form on step 1 if no step has been specified. 
    $items['user/register']['page arguments'] = array('register');
    $items['user/register']['file path'] = drupal_get_path('module', 'sharemyride_registration');
    $items['user/register']['file'] = 'sharemyride_registration_ctools_wizard.inc';
    return $items;
}

/** * Implements hook_menu(). */
function sharemyride_registration_menu() {
    $items['user/register/%'] = array(
        'title' => 'Create new account',
        'page callback' => 'sharemyride_registration_ctools_wizard',
        'page arguments' => array(2),
        'access callback' => 'sharemyride_registration_access',
        'access arguments' =>
        array(2),
        'file' => 'sharemyride_registration_ctools_wizard.inc',
        'type' => MENU_CALLBACK,);
    return $items;
}

    function sharemyride_registration_access($step){
            
        if(user_is_anonymous()){
                return TRUE;
            }else{
                return FALSE;
            }
    }
/** * Implements hook_form_FORM_ID_alter(). */
function sharemyride_registration_form_user_register_form_alter(&$form, &$form_state) {
    drupal_set_message('Form Alter');
    ctools_include('wizard');
    $form['#submit'] = array('user_register_submit', 'ctools_wizard_submit',);
}
